### PR TITLE
Add Watermark

### LINKED ISSUE #5: [PROD] Convert project banner into watermark
logo 

# Problem
The current project banner takes up too much space for which it has no real use. See screenshot:

image

# Objectives
Following the update of Desktop version of the StatsBox (SB) (see #4 ), we would need to 

In general, we indent to:
- To reduce the visual impact of the project banner.
- To keep the project properly identified in the MAP.
 
# Proposed solution
- [ ] Design a PLD Watermark
- [ ] Incorporate the PLD Watermark in the MAP
- [ ] Give the Watermark a URL to https://ProjectLockdown.world

# Extra information
- Must have
 -- PLD Watermark to appear at all times. Possible configurations to be implemented later on.
 -- Integrate in a way that minimizes visual disturbance and avoids UX issues to the users.

- Should have
 -- Nil

- Could have
 -- Nil

- Won't have
 -- Nil

# Resources
## Other documentation resources

PLD Website:
https://ProjectLockdown.world

# Tests

# Related Issues
#4 

**Problem**

**Objectives**

Since the final mockup is still pending, the best course of action would be
- Create a text-based sample (Project Lockdown)
- Apply some basic CSS
- Position Top Left of the MAP
Once we have the final mockup we will proceed with the final retouches.

**Mockup**
image

**Pending**
- Final mockup for the watermark.
@TheIOFoundation/tiof-pld-team-uxui 

**Related Issues**
Ignore the StatsBox as it is being treated in a separate Issue: https://github.com/TheIOFoundation/ProjectLockdown/issues/4

### PR DESCRIPTION
**Pull request by stanley-miao**
Resolves #5

### CODE REVIEW

**Comment by jeff-knurek** [comment]
This looks good to me based on the description in #5  (due to not having a final mockup/design)
Screenshot from 2021-05-06 13-35-56

my one suggestion for change is that maybe you can change it so that the font size scales 
Screenshot from 2021-05-06 13-36-44

**Comment by JFQueralt** [comment]
Yeah, the ideal situation is a smaller font that adapts to the viewport.
I was thinking something along the lines of what Mapbox does though clearly since we don't have a reference design that makes things harder. 

@YehualashetGit can you look into this?

BTW, working with Joey to get Figma more easy to use. Plus the Overlay plugin.

**Comment by YehualashetGit** [comment]
> Yeah, the ideal situation is a smaller font that adapts to the viewport.
> I was thinking something along the lines of what Mapbox does though clearly since we don't have a reference design that makes things harder.
> 
> @YehualashetGit can you look into this?
> 
> BTW, working with Joey to get Figma more easy to use. Plus the Overlay plugin.

**Comment by stanley-miao** [comment]
> Yeah, the ideal situation is a smaller font that adapts to the viewport.
> I was thinking something along the lines of what Mapbox does though clearly since we don't have a reference design that makes things harder.
> 
> @YehualashetGit can you look into this?
> 
> BTW, working with Joey to get Figma more easy to use. Plus the Overlay plugin.

Is this what you're looking for? I switched font-size from px to vw, and added a slider to the Storybook.

**Comment by stanley-miao** [comment]
Screen Shot 2021-05-06 at 3 14 40 AM

Screen Shot 2021-05-06 at 3 13 33 AM

**Review by jeff-knurek — APPROVED** [review]
yeah, that works for me. there is a point at which it gets too small and doesn't work well, but we can look into dealing with that once we have something better than just text

**Review by jeff-knurek — COMMENTED** [review]
sorry @stanley-miao one last adjustment needed. The padding of the `top` vs `left` of the text is not equal, can you square that up before merging this.

**Comment by stanley-miao** [comment]
> sorry @stanley-miao one last adjustment needed. The padding of the `top` vs `left` of the text is not equal, can you square that up before merging this.

Should the padding adapt to the viewport as well? Right now it's set to px.

**Comment by jeff-knurek** [comment]
perfect, that works

**Pull request merged**
